apiVersion: v1
kind: ConfigMap
metadata:
  name: recipe-data-sample
  labels:
    app.kubernetes.io/name: recipe-data
data:
  recipe.json: |
    {
      "version": "1.0.0",
      "releaseDate": "2026-02-01",
      "components": [
        {
          "name": "Component A",
          "version": "1.2.3",
          "type": "firmware"
        }
      ]
    }
